version: '3.8'

volumes:
  postgres-data:

    null
services:
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5433:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PGADMIN_DEFAULT_EMAIL: zli@example.com
      PGADMIN_DEFAULT_PASSWORD: zli*123
